services:
  socnet.api-1:
    image: socnet.api
    build:
      context: .
      dockerfile: SocNet.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgres
      - redis
      - mongo

  socnet.api-2:
    image: socnet.api
    build:
      context: .
      dockerfile: SocNet.Api/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - postgres
      - redis
      - mongo
      
  postgres:
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: socnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

volumes:
  postgres_data:
    driver: local